### ISSUE TITLE
Name of new Release: This is NOT 2.19.0

### ISSUE THREAD

**Issue by uschaett** [COSMO-ORG/eccodes-cosmo-resources#1]
A new tag v2.19.0.6 has been created, but these definitions are for eccodes version 2.23.0, which is stated correctedly in the description. But to avoid confusion and problems, I strongly recommend to rename this tag with 2.23.0 or 2.23.0.1 (to allow further updates in the definitions for version 2.23.0

**Comment by uschaett** [comment]
@jmbettems @owm-mch I am not sure, whether anybody saw that issue regarding eccodes-cosmo-resources, so I thought to write this comment: Please take a look at Issue #1

**Comment by owm-mch** [comment]
The new tag refers to an updated version of 2.19.05: I extracted the new pollen parameter definitions for CORY and emission tuning from eccodes_definitions.edzw-2.23.0-4 and added them to 2.19.05 to build the new release. We did not want to upgrade to eccodes 2.23 right now at MeteoSwiss.

**Comment by uschaett** [comment]
@owm-mch @jmbettems Oh, sorry for the noise then!

**Comment by owm-mch** [comment]
Dear Uli,

I think that this is a misunderstanding. See my comment (i.e. the one of owm-mch) of GitHub. We needed an intermediate version of the eccodes-cosmo-rsources based on 2.19, which supports the new CORY pollen parameters and the emission tuning parameter.

Sebastian had told me that I could download the new eccodes_definitions.edzw-2.23.0-4.tar.bz2 from https://opendata.dwd.de/weather/lib/grib/.

I have to admit that I know that you usually prepare the new definitions for COSMO, but I am not sure where you publish them.

Best regards,
Petra

**Comment by uschaett** [comment]
@owm-mch Yes, sorry. It was just because last Thursday I sent the 2.23.0 to you and did not take a closer look to the changes here. For COSMO partners having access to github, this repository is the reference, where people can get the definition files. For other partners we usually publish the definitions together with new versions of INT2LM (because everybody needs the GRIB 2 definition for reading ICON data with INT2LM).

**Comment by owm-mch** [comment]
Dear Uli,

to whom did you send the definitions 2.23.0? We did not receive any mail from you.

Best regards,
Petra

**Comment by uschaett** [comment]
@owm-mch I sent it to you at Petra.Baumann@meteoswiss.ch, just last Thursday
![SentMail_25 11 21](https://user-images.githubusercontent.com/16255959/144077509-19f35057-3c61-4c9b-9812-de18a9a40cda.png)

**Comment by owm-mch** [comment]
Dear Uli,

I actually did not receive that mail – neither in my inbox nor in the spam folder. I will contact our IT!

Many greetings and thanks for these clarifications,
Petra
